// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Microsoft.Exchange.Data {

  /// <summary>Holder for reflection information generated from test.proto</summary>
  public static partial class TestReflection {

    #region Descriptor
    /// <summary>File descriptor for test.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgp0ZXN0LnByb3RvIrMBChVEaXJlY3RvcnlJZGVudGl0eURhdGESDAoEbmFt",
            "ZRgBIAEoCRIRCglvYmplY3RfaWQYAiABKAkSGQoRb3JnYW5pemF0aW9uX2d1",
            "aWQYAyABKAkSFgoOcGFydGl0aW9uX2ZxZG4YBSABKAkSFQoNZGF0YWJhc2Vf",
            "Z3VpZBgGIAEoCRIaChJkaXN0aW5ndWlzaGVkX25hbWUYByABKAkSEwoLZm9y",
            "ZXN0X25hbWUYCCABKAlCGqoCF01pY3Jvc29mdC5FeGNoYW5nZS5EYXRhYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.Exchange.Data.DirectoryIdentityData), global::Microsoft.Exchange.Data.DirectoryIdentityData.Parser, new[]{ "Name", "ObjectId", "OrganizationGuid", "PartitionFqdn", "DatabaseGuid", "DistinguishedName", "ForestName" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DirectoryIdentityData : pb::IMessage<DirectoryIdentityData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DirectoryIdentityData> _parser = new pb::MessageParser<DirectoryIdentityData>(() => new DirectoryIdentityData());
    private pb::UnknownFieldSet _unknownFields;

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    private scg::IEqualityComparer<DirectoryIdentityData> Comparer { get; set; } = new DefaultDirectoryIdentityDataComparer();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DirectoryIdentityData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.Exchange.Data.TestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DirectoryIdentityData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DirectoryIdentityData(DirectoryIdentityData other) : this() {
      name_ = other.name_;
      objectId_ = other.objectId_;
      organizationGuid_ = other.organizationGuid_;
      partitionFqdn_ = other.partitionFqdn_;
      databaseGuid_ = other.databaseGuid_;
      distinguishedName_ = other.distinguishedName_;
      forestName_ = other.forestName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DirectoryIdentityData Clone() {
      return new DirectoryIdentityData(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "object_id" field.</summary>
    public const int ObjectIdFieldNumber = 2;
    private string objectId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ObjectId {
      get { return objectId_; }
      set {
        objectId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "organization_guid" field.</summary>
    public const int OrganizationGuidFieldNumber = 3;
    private string organizationGuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrganizationGuid {
      get { return organizationGuid_; }
      set {
        organizationGuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "partition_fqdn" field.</summary>
    public const int PartitionFqdnFieldNumber = 5;
    private string partitionFqdn_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PartitionFqdn {
      get { return partitionFqdn_; }
      set {
        partitionFqdn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "database_guid" field.</summary>
    public const int DatabaseGuidFieldNumber = 6;
    private string databaseGuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DatabaseGuid {
      get { return databaseGuid_; }
      set {
        databaseGuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "distinguished_name" field.</summary>
    public const int DistinguishedNameFieldNumber = 7;
    private string distinguishedName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DistinguishedName {
      get { return distinguishedName_; }
      set {
        distinguishedName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "forest_name" field.</summary>
    public const int ForestNameFieldNumber = 8;
    private string forestName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ForestName {
      get { return forestName_; }
      set {
        forestName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DirectoryIdentityData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DirectoryIdentityData other) {
      return this.Comparer.Equals(this, other);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      return this.Comparer.GetHashCode(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (ObjectId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ObjectId);
      }
      if (OrganizationGuid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OrganizationGuid);
      }
      if (PartitionFqdn.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PartitionFqdn);
      }
      if (DatabaseGuid.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DatabaseGuid);
      }
      if (DistinguishedName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(DistinguishedName);
      }
      if (ForestName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ForestName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (ObjectId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ObjectId);
      }
      if (OrganizationGuid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OrganizationGuid);
      }
      if (PartitionFqdn.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PartitionFqdn);
      }
      if (DatabaseGuid.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DatabaseGuid);
      }
      if (DistinguishedName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(DistinguishedName);
      }
      if (ForestName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ForestName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (ObjectId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObjectId);
      }
      if (OrganizationGuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganizationGuid);
      }
      if (PartitionFqdn.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PartitionFqdn);
      }
      if (DatabaseGuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DatabaseGuid);
      }
      if (DistinguishedName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DistinguishedName);
      }
      if (ForestName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ForestName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DirectoryIdentityData other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.ObjectId.Length != 0) {
        ObjectId = other.ObjectId;
      }
      if (other.OrganizationGuid.Length != 0) {
        OrganizationGuid = other.OrganizationGuid;
      }
      if (other.PartitionFqdn.Length != 0) {
        PartitionFqdn = other.PartitionFqdn;
      }
      if (other.DatabaseGuid.Length != 0) {
        DatabaseGuid = other.DatabaseGuid;
      }
      if (other.DistinguishedName.Length != 0) {
        DistinguishedName = other.DistinguishedName;
      }
      if (other.ForestName.Length != 0) {
        ForestName = other.ForestName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            ObjectId = input.ReadString();
            break;
          }
          case 26: {
            OrganizationGuid = input.ReadString();
            break;
          }
          case 42: {
            PartitionFqdn = input.ReadString();
            break;
          }
          case 50: {
            DatabaseGuid = input.ReadString();
            break;
          }
          case 58: {
            DistinguishedName = input.ReadString();
            break;
          }
          case 66: {
            ForestName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            ObjectId = input.ReadString();
            break;
          }
          case 26: {
            OrganizationGuid = input.ReadString();
            break;
          }
          case 42: {
            PartitionFqdn = input.ReadString();
            break;
          }
          case 50: {
            DatabaseGuid = input.ReadString();
            break;
          }
          case 58: {
            DistinguishedName = input.ReadString();
            break;
          }
          case 66: {
            ForestName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested comparer
    private class DefaultDirectoryIdentityDataComparer : scg::IEqualityComparer<DirectoryIdentityData> {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(DirectoryIdentityData x, DirectoryIdentityData y) {
        if (ReferenceEquals(x, null) && ReferenceEquals(y, null)) {
          return true;  }
        if (ReferenceEquals(x, null) || ReferenceEquals(y, null)) {
          return false;
        }
        if (ReferenceEquals(x, y)) {
          return true;
        }
        if (!x.Name.Equals(y.Name)) return false;
        if (!x.ObjectId.Equals(y.ObjectId)) return false;
        if (!x.OrganizationGuid.Equals(y.OrganizationGuid)) return false;
        if (!x.PartitionFqdn.Equals(y.PartitionFqdn)) return false;
        if (!x.DatabaseGuid.Equals(y.DatabaseGuid)) return false;
        if (!x.DistinguishedName.Equals(y.DistinguishedName)) return false;
        if (!x.ForestName.Equals(y.ForestName)) return false;
        return Equals(x._unknownFields, y._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int GetHashCode(DirectoryIdentityData obj) {
        int hash = 1;
        if (obj.Name.Length != 0) hash ^= obj.Name.GetHashCode();
        if (obj.ObjectId.Length != 0) hash ^= obj.ObjectId.GetHashCode();
        if (obj.OrganizationGuid.Length != 0) hash ^= obj.OrganizationGuid.GetHashCode();
        if (obj.PartitionFqdn.Length != 0) hash ^= obj.PartitionFqdn.GetHashCode();
        if (obj.DatabaseGuid.Length != 0) hash ^= obj.DatabaseGuid.GetHashCode();
        if (obj.DistinguishedName.Length != 0) hash ^= obj.DistinguishedName.GetHashCode();
        if (obj.ForestName.Length != 0) hash ^= obj.ForestName.GetHashCode();
        if (obj._unknownFields != null) {
          hash ^= obj._unknownFields.GetHashCode();
        }
        return hash;
      }
    }

    #endregion
  }

  #endregion

}

#endregion Designer generated code
